// Copyright (c) 2026 Jon Marcum
// Licensed under the MIT License. See LICENSE-MIT in the repository root.

/**
 * @module binaryen-ts/tools/witgen
 *
 * A `.wit` from a module's CORE signatures — the interface floor a binary
 * carries: `i32 → s32`, `i64 → s64`, `f32`, `f64`. A string that crosses as
 * `(ptr, len)` shows as two `s32`s, and the header says so. An export whose
 * signature has no WIT form (v128, references, several results) or whose
 * name is not a WIT identifier is left out and LISTED in a comment, never
 * silently dropped. Runtime plumbing (`_start`, `__…`, `cabi_…`, the
 * toolchains' allocator exports) is not the module's interface and is not
 * listed.
 *
 * `wasm-bundle` writes one beside every bundle by default (owner,
 * 2026-10-08: "automatically generate the wit file when a bundled wasm file
 * is created as a default feature"). The shape is wasmtk's `witgen` — the
 * same kebab-casing, the same world layout — so what consumed their
 * generated file consumes ours.
 *
 * @license MIT
 */

import { readFile, writeFile } from 'node:fs/promises';
import { basename } from 'node:path';
import type { WasmModule } from '../ir/module.ts';
import { ExternalKind } from '../../wabt-ts/core/binary.ts';
import { Type } from '../../wabt-ts/core/types.ts';
import {
  type FuncSignature,
  isRefValueType,
  type Module,
  type ValueType,
  type Var,
} from '../../wabt-ts/ir/ir.ts';

/** The first line of every generated file — what says a `.wit` may be replaced. */
export const WIT_GENERATED_HEADER =
  '// Generated by binaryang from core wasm signatures — do not edit manually';

/** A file another generator wrote from core signatures (wasmtk's `witgen`): replaceable too. */
const GENERATED_BY = /^\/\/ Generated by (binaryang|wasmtk) from core wasm signatures/;

/** wasic's `toKebabCase`, so names line up with its `.wit` and bindgen's resolution. */
export function toKebabCase(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
}

/** A WIT identifier: kebab words, each starting with a letter. */
const WIT_ID = /^[a-z][a-z0-9]*(-[a-z][a-z0-9]*)*$/;

/** TinyGo's libc / float runtime exports: in every TinyGo module, not the author's API. */
const TOOLCHAIN_RUNTIME_EXPORTS: ReadonlySet<string> = new Set([
  'malloc',
  'free',
  'calloc',
  'realloc',
  'fminimum',
  'fminimumf',
  'fmaximum',
  'fmaximumf',
]);

function isInternalExport(name: string): boolean {
  return name === '_start' || name === '_initialize' || name === 'abort' || name.startsWith('__') ||
    name.startsWith('cabi_') || name.startsWith('asyncify_') || name.includes('config-schema') ||
    TOOLCHAIN_RUNTIME_EXPORTS.has(name);
}

function coreToWit(t: ValueType): string | null {
  if (isRefValueType(t)) return null;
  switch (t) {
    case Type.I32:
      return 's32';
    case Type.I64:
      return 's64';
    case Type.F32:
      return 'f32';
    case Type.F64:
      return 'f64';
    default:
      return null; // v128, references
  }
}

/** A function's WIT signature from its core type, or the reason it has none. */
function witSig(sig: FuncSignature): { sig: string } | { why: string } {
  if (sig.results.length > 1) return { why: 'multiple results' };
  const pw = sig.params.map(coreToWit);
  const rw = sig.results.map(coreToWit);
  if (pw.includes(null) || rw.includes(null)) {
    return { why: 'a core type with no WIT form (v128/reference)' };
  }
  const params = pw.map((t, i) => `p${i}: ${t}`).join(', ');
  return { sig: `func(${params})${rw.length ? ` -> ${rw[0]}` : ''}` };
}

/** The signature of the function `v` names, imports first in the index space. */
function signatureOf(m: Module, v: Var): FuncSignature | undefined {
  const funcs: { name: string; typeVar?: Var; sig: FuncSignature }[] = [];
  for (const imp of m.imports) if (imp.kind === ExternalKind.Func) funcs.push(imp.func);
  funcs.push(...m.functions);
  const f = v.kind === 'index' ? funcs[v.value] : funcs.find((x) => x.name === v.name);
  if (f === undefined) return undefined;
  if (f.typeVar !== undefined) {
    const t = f.typeVar.kind === 'index'
      ? m.types[f.typeVar.value]
      : m.types.find((x) => x.name === (f.typeVar as { name: string }).name);
    if (t !== undefined && t.kind === 'func') return t.sig;
  }
  return f.sig;
}

/** A package / world name from `name`: kebab-cased, made an identifier (`bundle` if nothing is left). */
export function witWorldName(name: string): string {
  const id = toKebabCase(name).replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-')
    .replace(/^[^a-z]+/, '').replace(/-$/, '');
  return WIT_ID.test(id) ? id : 'bundle';
}

/**
 * The `.wit` of `m`: its exported functions as a world named after `name`.
 * Non-WASI function IMPORTS are listed by name in a comment — the loader
 * must provide them — not described.
 */
export function witFromModule(m: WasmModule, name: string): string {
  const pkg = witWorldName(name);
  const exports: string[] = [];
  const skipped: string[] = [];
  const hostImports = m.imports
    .filter((i) => i.kind === ExternalKind.Func && i.module !== 'wasi_snapshot_preview1')
    .map((i) => `${i.module}.${i.field}`);
  for (const ex of m.exports) {
    if (ex.kind !== ExternalKind.Func || isInternalExport(ex.name)) continue;
    const id = toKebabCase(ex.name);
    const sig = signatureOf(m, ex.var);
    if (sig === undefined) {
      skipped.push(`export ${ex.name}: names no function`);
      continue;
    }
    const s = witSig(sig);
    if (!WIT_ID.test(id)) skipped.push(`export ${ex.name}: not a WIT identifier`);
    else if ('why' in s) skipped.push(`export ${ex.name}: ${s.why}`);
    else exports.push(`  export ${id}: ${s.sig};`);
  }
  return [
    WIT_GENERATED_HEADER,
    '// Core types only: a string or record crosses as (ptr, len)/pointers and shows as s32s here.',
    ...skipped.map((s) => `// skipped ${s}`),
    ...(hostImports.length
      ? [
        `// host imports (types not derived; provide them to the loader): ${
          hostImports.join(', ')
        }`,
      ]
      : []),
    `package local:${pkg};`,
    '',
    `world ${pkg} {`,
    ...exports,
    '}',
    '',
  ].join('\n');
}

/** Whether `text` describes anything — an export, a skip, or a host import. */
export function witSaysSomething(text: string): boolean {
  return /^ {2}export |^\/\/ skipped |^\/\/ host imports/m.test(text);
}

/**
 * Write `text` as `<wasmPath minus .wasm>.wit`, unless a BETTER file is there
 * already — one not generated from core signatures (a hand-written one, or
 * wasic's from source types) is kept and said so — or `text` describes
 * nothing (a program exporting only `_start`): an empty world is noise.
 * Returns what happened, for the log.
 */
export async function emitWitBeside(
  wasmPath: string,
  text: string,
): Promise<{ path: string; outcome: 'written' | 'kept existing' | 'nothing to describe' }> {
  const path = wasmPath.replace(/\.wasm$/i, '') + '.wit';
  if (!witSaysSomething(text)) return { path, outcome: 'nothing to describe' };
  let existing: string | null = null;
  try {
    existing = new TextDecoder().decode(await readFile(path));
  } catch {
    // absent
  }
  if (existing !== null && !GENERATED_BY.test(existing)) return { path, outcome: 'kept existing' };
  await writeFile(path, text);
  return { path, outcome: 'written' };
}

/** The world name a `.wasm` path gives: its basename without the extension. */
export function witNameOf(wasmPath: string): string {
  return basename(wasmPath).replace(/\.(wasm|wat)$/i, '');
}
