// Copyright (c) 2026 Jon Marcum
// Licensed under the MIT License. See LICENSE-MIT in the repository root.

/**
 * The shared definitions (open-work 22; the workspace's D2 / D3): the JSON
 * sources in `src/definitions/` are the truth. This script
 *
 * - stamps each source's `sha256` — over its canonical content, the hash field
 *   itself left empty — and
 * - GENERATES `src/definitions/data.ts`, the typed constants `./definitions`
 *   exports, from them.
 *
 * `--check` changes nothing: it fails when a stated hash is stale or the
 * generated module differs from what the sources generate — the same check a
 * consumer runs on its own copy. With `--prepared <dir>...` (prepared spec
 * suites, `deno task spec:prepare`) it also proves D3 covers every
 * expected-failure message those suites write.
 *
 *   deno task definitions                 # stamp and generate
 *   deno task definitions --check [--prepared <dir>...]
 */

const DIR = new URL('../src/definitions/', import.meta.url);
const SOURCES = ['opcodes.json', 'features.json', 'verdicts.json'] as const;
const OUT = new URL('data.ts', DIR);

/** JSON with object keys sorted, no whitespace: what the hash is over. */
function canonical(v: unknown): string {
  if (Array.isArray(v)) return `[${v.map(canonical).join(',')}]`;
  if (v !== null && typeof v === 'object') {
    const o = v as Record<string, unknown>;
    return `{${
      Object.keys(o).sort().map((k) => `${JSON.stringify(k)}:${canonical(o[k])}`).join(',')
    }}`;
  }
  return JSON.stringify(v);
}

export async function contentHash(source: Record<string, unknown>): Promise<string> {
  const bytes = new TextEncoder().encode(canonical({ ...source, sha256: '' }));
  const digest = new Uint8Array(await crypto.subtle.digest('SHA-256', bytes));
  return [...digest].map((b) => b.toString(16).padStart(2, '0')).join('');
}

async function fmt(ts: string): Promise<string> {
  const p = new Deno.Command(Deno.execPath(), {
    args: ['fmt', '--ext=ts', '-'],
    cwd: new URL('..', import.meta.url),
    stdin: 'piped',
    stdout: 'piped',
  }).spawn();
  const w = p.stdin.getWriter();
  await w.write(new TextEncoder().encode(ts));
  await w.close();
  const out = await p.output();
  if (!out.success) throw new Error('deno fmt failed on the generated module');
  return new TextDecoder().decode(out.stdout);
}

function generate(sources: Record<string, Record<string, unknown>>): string {
  const o = sources['opcodes.json']!;
  const f = sources['features.json']!, v = sources['verdicts.json']!;
  const lit = (x: unknown) => JSON.stringify(x, null, 2);
  return `// GENERATED by scripts/definitions.ts from src/definitions/opcodes.json,
// features.json and verdicts.json — do not edit; edit the JSON and run
// \`deno task definitions\`.

import type { FeatureDefinitions, OpcodeDefinitions, VerdictDefinitions } from './types.ts';

/** D1 — the WebAssembly instructions. */
export const OPCODE_DEFINITIONS: OpcodeDefinitions = ${lit(o)};

/** D2 — the WebAssembly feature / proposal list. */
export const FEATURE_DEFINITIONS: FeatureDefinitions = ${lit(f)};

/** D3 — the verdict vocabulary. */
export const VERDICT_DEFINITIONS: VerdictDefinitions = ${lit(v)};
`;
}

async function read(): Promise<Record<string, Record<string, unknown>>> {
  const out: Record<string, Record<string, unknown>> = {};
  for (const s of SOURCES) out[s] = JSON.parse(await Deno.readTextFile(new URL(s, DIR)));
  return out;
}

/** Every distinct message `type` assertions write in the prepared suites under `dirs`. */
function preparedMessages(dirs: string[], types: Set<string>): Map<string, string> {
  const found = new Map<string, string>();
  for (const root of dirs) {
    for (const d of Deno.readDirSync(root)) {
      if (!d.isDirectory) continue;
      let j: { commands: { type: string; text?: string }[] };
      try {
        j = JSON.parse(Deno.readTextFileSync(`${root}/${d.name}/${d.name}.json`));
      } catch {
        continue;
      }
      for (const c of j.commands) {
        if (c.text !== undefined && types.has(c.type)) found.set(c.text, `${d.name} (${c.type})`);
      }
    }
  }
  return found;
}

if (import.meta.main) {
  const args = Deno.args.slice();
  const check = args.includes('--check');
  const pi = args.indexOf('--prepared');
  const prepared = pi >= 0 ? args.slice(pi + 1).filter((a) => !a.startsWith('--')) : [];
  const sources = await read();
  let bad = 0;

  for (const s of SOURCES) {
    const want = await contentHash(sources[s]!);
    if (sources[s]!.sha256 === want) continue;
    if (check) {
      console.error(
        `✗ ${s}: sha256 is stale (states ${sources[s]!.sha256 || '""'}, content is ${want})`,
      );
      bad++;
    } else {
      const path = new URL(s, DIR);
      const text = await Deno.readTextFile(path);
      await Deno.writeTextFile(path, text.replace(/"sha256": "[0-9a-f]*"/, `"sha256": "${want}"`));
      sources[s]!.sha256 = want;
      console.log(`stamped ${s}: ${want}`);
    }
  }

  const generated = await fmt(generate(sources));
  const current = await Deno.readTextFile(OUT).catch(() => '');
  if (generated !== current) {
    if (check) {
      console.error('✗ src/definitions/data.ts differs from what the sources generate');
      bad++;
    } else {
      await Deno.writeTextFile(OUT, generated);
      console.log('generated src/definitions/data.ts');
    }
  }

  if (prepared.length > 0) {
    const entries = sources['verdicts.json']!.entries as { message: string; verdict: string }[];
    const types = new Set(['assert_trap', 'assert_exhaustion']);
    const messages = preparedMessages(prepared, types);
    for (const [text, where] of messages) {
      if (!entries.some((e) => text.startsWith(e.message))) {
        console.error(`✗ D3 has no class for ${JSON.stringify(text)} — ${where}`);
        bad++;
      }
    }
    console.log(
      `D3 covers ${messages.size} distinct trap / exhaustion messages in ${prepared.length} prepared root(s)`,
    );
  }

  if (bad > 0) Deno.exit(1);
  console.log(check ? 'definitions: up to date' : 'definitions: done');
}
